### ISSUE TITLE
[BUG] feed2toot broken after last update

### ISSUE THREAD

**Issue by marcogiorgio** [linuxserver/docker-feed2toot#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi
I noticed that feed2toot broke after the last update.
I keep getting the error shown in the log

### Steps To Reproduce

Update to latest feed2toot (0.17-ls26)

### Environment

```markdown
Debian 11 - Official Docker repo
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "2.1"
services:
  feed2toot:
    image: lscr.io/linuxserver/feed2toot:latest
    container_name: feed2toot
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - ./config:/config
```

### Container logs

```bash
python3: can't open file '/usr/bin/feed2toot': [Errno 2] No such file or directory

python3: can't open file '/usr/bin/feed2toot': [Errno 2] No such file or directory

python3: can't open file '/usr/bin/feed2toot': [Errno 2] No such file or directory

python3: can't open file '/usr/bin/feed2toot': [Errno 2] No such file or directory
```

**Comment by Roxedus** [comment]
Thanks for the report, can you give the this image a try? ghcr.io/linuxserver/lspipepr-feed2toot:0.17-pkg-bacdc265-dev-2dcbc1a9010ce20b45abe75987a4f49e3ead6471-pr-11

**Comment by marcogiorgio** [comment]
I get this error while trying to pull the image:

`Error response from daemon: Head "https://ghcr.io/v2/linuxserver/lspipepr-feed2toot/manifests/0.17-pkg-bacdc265-dev-2dcbc1a9010ce20b45abe75987a4f49e3ead6471-pr-11": unauthorized`

**Comment by thespad** [comment]
Looks like something went wrong with the GHCR push of the image, can you try `lspipepr-feed2toot:0.17-pkg-bacdc265-dev-2dcbc1a9010ce20b45abe75987a4f49e3ead6471-pr-11`

**Comment by marcogiorgio** [comment]
same error :-(

**Comment by thespad** [comment]
As in same error pulling, or same error when running the image?

**Comment by thespad** [comment]
Sorry, I'm an idiot, it should have been `lspipepr/feed2toot:0.17-pkg-bacdc265-dev-2dcbc1a9010ce20b45abe75987a4f49e3ead6471-pr-11`

**Comment by marcogiorgio** [comment]
looks ok!

**Comment by thespad** [comment]
https://github.com/linuxserver/docker-feed2toot/pull/11 is merged and should build shortly

**Comment by marcogiorgio** [comment]
Thanks!
